// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/order-loading/CurrentProblem.tsx": () => import("../components/mockups/order-loading/CurrentProblem.tsx"),
  "./components/mockups/order-loading/MenuLoaded.tsx": () => import("../components/mockups/order-loading/MenuLoaded.tsx"),
  "./components/mockups/order-loading/SkeletonLoading.tsx": () => import("../components/mockups/order-loading/SkeletonLoading.tsx")
};
