from database import db
from datetime import datetime
from sqlalchemy.orm import validates as _validates
from sanitize_html import sanitize_html as _sanitize_html

class SiteSettings(db.Model):
    __tablename__ = 'site_settings'
    id = db.Column(db.Integer, primary_key=True)
    site_name_he = db.Column(db.String(100), default='סומו')
    site_name_en = db.Column(db.String(100), default='SUMO')
    hero_title_he = db.Column(db.String(200), default='סומו')
    hero_title_en = db.Column(db.String(200), default='SUMO')
    hero_subtitle_he = db.Column(db.String(200), default='מטבח אסייתי אותנטי')
    hero_subtitle_en = db.Column(db.String(200), default='Authentic Asian Kitchen')
    hero_description_he = db.Column(db.Text, default='חוויה קולינרית ייחודית של טעמי אסיה')
    hero_description_en = db.Column(db.Text, default='A unique culinary experience of Asian flavors')
    about_title_he = db.Column(db.String(200))
    about_title_en = db.Column(db.String(200))
    about_content_he = db.Column(db.Text)
    about_content_en = db.Column(db.Text)
    facebook_url = db.Column(db.String(255))
    instagram_url = db.Column(db.String(255))
    whatsapp_number = db.Column(db.String(20))
    hero_desktop_image = db.Column(db.String(255))
    logo_image = db.Column(db.String(255))
    favicon_image = db.Column(db.String(255))
    primary_color = db.Column(db.String(20), default='#1a3a6e')
    accent_color = db.Column(db.String(20), default='#dc3545')
    enable_online_ordering = db.Column(db.Boolean, default=True)
    enable_english_language = db.Column(db.Boolean, default=True)
    enable_delivery = db.Column(db.Boolean, default=True)
    enable_pickup = db.Column(db.Boolean, default=True)
    enable_menu_display = db.Column(db.Boolean, default=True)
    enable_gallery = db.Column(db.Boolean, default=True)
    enable_gallery_section = db.Column(db.Boolean, default=True)
    enable_contact_form = db.Column(db.Boolean, default=True)
    enable_table_reservations = db.Column(db.Boolean, default=True)
    gallery_section_title_he = db.Column(db.String(200), default='גלריה')
    gallery_section_title_en = db.Column(db.String(200), default='Gallery')
    gallery_section_subtitle_he = db.Column(db.String(500))
    gallery_section_subtitle_en = db.Column(db.String(500))
    gallery_max_photos = db.Column(db.Integer, default=8)
    enable_app_download = db.Column(db.Boolean, default=True)
    app_store_url = db.Column(db.String(500))
    google_play_url = db.Column(db.String(500))
    app_promo_text_he = db.Column(db.String(200), default='הורידו את האפליקציה שלנו!')
    app_promo_text_en = db.Column(db.String(200), default='Download our app!')
    app_discount_text_he = db.Column(db.String(200), default='קבלו 10% הנחה בהזמנה הראשונה באפליקציה')
    app_discount_text_en = db.Column(db.String(200), default='Get 10% off your first app order')
    show_app_banner = db.Column(db.Boolean, default=True)
    app_banner_title_he = db.Column(db.String(200), default='הזמנות רק באפליקציה')
    app_banner_title_en = db.Column(db.String(200), default='Order via App')
    app_banner_subtitle_he = db.Column(db.String(200), default='הורידו עכשיו')
    app_banner_subtitle_en = db.Column(db.String(200), default='Download Now')
    minimum_order_amount = db.Column(db.Float, default=50)
    tax_rate = db.Column(db.Float, default=0.17)
    delivery_fee = db.Column(db.Float, default=15.0)
    free_delivery_threshold = db.Column(db.Float, default=100.0)
    estimated_delivery_time = db.Column(db.String(100), default='45-60')
    service_fee_percentage = db.Column(db.Float, default=0.0)
    currency_symbol = db.Column(db.String(10), default='₪')
    contact_form_email = db.Column(db.String(255), default='info@sumo-restaurant.co.il')
    catering_form_email = db.Column(db.String(255), default='info@sumo-restaurant.co.il')
    careers_form_email = db.Column(db.String(255), default='info@sumo-restaurant.co.il')
    contact_email_subject = db.Column(db.String(255), default='הודעה חדשה מהאתר')
    catering_email_subject = db.Column(db.String(255), default='פנייה חדשה לקייטרינג')
    careers_email_subject = db.Column(db.String(255), default='מועמדות חדשה לעבודה')
    enable_catering_section = db.Column(db.Boolean, default=True)
    catering_title_he = db.Column(db.String(200), default='קייטרינג ואירועים מיוחדים')
    catering_title_en = db.Column(db.String(200), default='Catering & Special Events')
    catering_subtitle_he = db.Column(db.Text, default='הביאו את הטעמים האסיאתיים האותנטיים לחגיגה הבאה שלכם. אנו מציעים תפריטי קייטרינג מותאמים אישית לחתונות, ימי הולדת ואירועי חברה.')
    catering_subtitle_en = db.Column(db.Text, default='Bring authentic Asian flavors to your next celebration. We offer custom catering menus for weddings, birthdays, and corporate events.')
    catering_image = db.Column(db.String(255))
    enable_catering_page = db.Column(db.Boolean, default=True)
    catering_page_hero_title_he = db.Column(db.String(200), default='קייטרינג ואירועים מיוחדים')
    catering_page_hero_title_en = db.Column(db.String(200), default='Catering & Special Events')
    catering_page_hero_subtitle_he = db.Column(db.Text, default='הפכו את האירוע שלכם לבלתי נשכח עם המטבח האסייתי האותנטי שלנו')
    catering_page_hero_subtitle_en = db.Column(db.Text, default='Make your event unforgettable with our authentic Asian cuisine')
    catering_page_gallery_title_he = db.Column(db.String(200), default='גלריה')
    catering_page_gallery_title_en = db.Column(db.String(200), default='Gallery')
    catering_page_gallery_subtitle_he = db.Column(db.String(500), default='צפו בתמונות מאירועים קודמים')
    catering_page_gallery_subtitle_en = db.Column(db.String(500), default='View photos from previous events')
    catering_page_cta_title_he = db.Column(db.String(200), default='מוכנים להפוך את האירוע שלכם למיוחד?')
    catering_page_cta_title_en = db.Column(db.String(200), default='Ready to Make Your Event Special?')
    catering_page_cta_subtitle_he = db.Column(db.String(500), default='צרו קשר עכשיו לייעוץ חינם ותפריט מותאם אישית')
    catering_page_cta_subtitle_en = db.Column(db.String(500), default='Contact us now for a free consultation and custom menu')
    enable_careers_section = db.Column(db.Boolean, default=True)
    careers_title_he = db.Column(db.String(200), default='הצטרפו לצוות שלנו')
    careers_title_en = db.Column(db.String(200), default='Join Our Team')
    careers_subtitle_he = db.Column(db.Text, default='מחפשים אנשי מקצוע מוכשרים להצטרף למשפחת סומו. גלו הזדמנויות קריירה מרגשות במטבח האסייתי המוביל.')
    careers_subtitle_en = db.Column(db.Text, default='Looking for talented professionals to join the SUMO family. Discover exciting career opportunities at the leading Asian kitchen.')
    careers_image = db.Column(db.String(255))
    careers_page_hero_title_he = db.Column(db.String(200), default='הצטרפו לצוות שלנו')
    careers_page_hero_title_en = db.Column(db.String(200), default='Join Our Team')
    careers_page_hero_subtitle_he = db.Column(db.Text, default='בואו להיות חלק ממשפחת סומו - מקום שבו כישרון פוגש תשוקה')
    careers_page_hero_subtitle_en = db.Column(db.Text, default='Be part of the SUMO family - where talent meets passion')
    careers_page_positions_title_he = db.Column(db.String(200), default='משרות פתוחות')
    deals_section_label_he = db.Column(db.String(200), default='מבצעים')
    deals_section_label_en = db.Column(db.String(200), default='Deals')
    careers_page_positions_title_en = db.Column(db.String(200), default='Open Positions')
    careers_page_positions_subtitle_he = db.Column(db.String(500), default='מצאו את המשרה המושלמת עבורכם')
    careers_page_positions_subtitle_en = db.Column(db.String(500), default='Find the perfect position for you')
    careers_page_cta_title_he = db.Column(db.String(200), default='מעוניינים להצטרף?')
    careers_page_cta_title_en = db.Column(db.String(200), default='Interested in Joining?')
    careers_page_cta_subtitle_he = db.Column(db.String(500), default='שלחו לנו את פרטיכם ונחזור אליכם בהקדם')
    careers_page_cta_subtitle_en = db.Column(db.String(500), default='Send us your details and we will get back to you soon')
    google_analytics_id = db.Column(db.String(50))
    google_tag_manager_id = db.Column(db.String(50))
    facebook_pixel_id = db.Column(db.String(50))
    maintenance_mode = db.Column(db.Boolean, default=False)
    announcement_text_he = db.Column(db.String(500))
    announcement_text_en = db.Column(db.String(500))
    announcement_enabled = db.Column(db.Boolean, default=False)
    announcement_bg_color = db.Column(db.String(20), default='#ffc107')
    enable_order_onboarding = db.Column(db.Boolean, default=True)
    ordering_paused = db.Column(db.Boolean, default=False)
    ordering_paused_message = db.Column(db.String(500))
    ordering_closed_message = db.Column(db.String(500))
    ordering_outside_hours_message = db.Column(db.String(500))
    enforce_ordering_hours = db.Column(db.Boolean, default=False)
    contact_phone = db.Column(db.String(20))
    admin_phone = db.Column(db.String(20))
    send_order_tracking_link = db.Column(db.Boolean, default=True)
    hyp_enabled = db.Column(db.Boolean, default=False)
    hyp_sandbox_mode = db.Column(db.Boolean, default=True)
    hyp_terminal = db.Column(db.String(50))
    hyp_api_key = db.Column(db.String(200))
    hyp_passp = db.Column(db.String(200))
    telegram_bot_token = db.Column(db.String(200))
    telegram_chat_id = db.Column(db.String(100))
    telegram_channel_id = db.Column(db.String(100))
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class CustomSection(db.Model):
    __tablename__ = 'custom_sections'
    id = db.Column(db.Integer, primary_key=True)
    title_he = db.Column(db.String(200), nullable=False)
    title_en = db.Column(db.String(200), nullable=False)
    content_he = db.Column(db.Text)
    content_en = db.Column(db.Text)
    section_type = db.Column(db.String(50), default='text')
    embed_code = db.Column(db.Text)
    background_color = db.Column(db.String(20), default='#ffffff')
    text_color = db.Column(db.String(20), default='#333333')
    is_active = db.Column(db.Boolean, default=True)
    display_order = db.Column(db.Integer, default=0)
    show_on_homepage = db.Column(db.Boolean, default=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    @_validates('content_he', 'content_en', 'embed_code')
    def _sanitize_content(self, key, value):
        if value and self.section_type in ('html', 'embed'):
            return _sanitize_html(value)
        return value

class ReservationSettings(db.Model):
    __tablename__ = 'reservation_settings'
    id = db.Column(db.Integer, primary_key=True)
    enable_reservations = db.Column(db.Boolean, default=True)
    reservation_system_url = db.Column(db.String(500))
    reservation_button_text_he = db.Column(db.String(100), default='הזמינו שולחן')
    reservation_button_text_en = db.Column(db.String(100), default='Reserve a Table')
    section_title_he = db.Column(db.String(200), default='הזמנת שולחן')
    section_title_en = db.Column(db.String(200), default='Table Reservation')
    section_description_he = db.Column(db.Text, default='הזמינו שולחן מראש ותיהנו מחוויה מושלמת')
    section_description_en = db.Column(db.Text, default='Reserve a table in advance and enjoy the perfect experience')
    show_on_homepage = db.Column(db.Boolean, default=True)
    display_order = db.Column(db.Integer, default=5)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class MediaFile(db.Model):
    __tablename__ = 'media_files'
    id = db.Column(db.Integer, primary_key=True)
    filename = db.Column(db.String(255), nullable=False)
    file_path = db.Column(db.String(500), nullable=False)
    file_type = db.Column(db.String(50))
    section = db.Column(db.String(100))
    is_active = db.Column(db.Boolean, default=True)
    display_order = db.Column(db.Integer, default=0)
    caption_he = db.Column(db.String(255))
    caption_en = db.Column(db.String(255))
    uploaded_at = db.Column(db.DateTime, default=datetime.utcnow)

class TermsOfUse(db.Model):
    __tablename__ = 'terms_of_use'
    id = db.Column(db.Integer, primary_key=True)
    content_he = db.Column(db.Text, nullable=False)
    content_en = db.Column(db.Text, nullable=False)
    last_updated_by = db.Column(db.String(100))
    is_active = db.Column(db.Boolean, default=True)
    effective_date = db.Column(db.DateTime, default=datetime.utcnow)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f'<TermsOfUse {self.id}>'

class PrivacyPolicy(db.Model):
    __tablename__ = 'privacy_policy'
    id = db.Column(db.Integer, primary_key=True)
    content_he = db.Column(db.Text, nullable=False)
    content_en = db.Column(db.Text, nullable=False)
    last_updated_by = db.Column(db.String(100))
    is_active = db.Column(db.Boolean, default=True)
    effective_date = db.Column(db.DateTime, default=datetime.utcnow)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f'<PrivacyPolicy {self.id}>'

class ConsentSettings(db.Model):
    __tablename__ = 'consent_settings'
    id = db.Column(db.Integer, primary_key=True)
    consent_type = db.Column(db.String(50), unique=True, nullable=False)
    display_name_he = db.Column(db.String(100), nullable=False)
    display_name_en = db.Column(db.String(100), nullable=False)
    consent_text_he = db.Column(db.Text, nullable=False)
    consent_text_en = db.Column(db.Text, nullable=False)
    is_required = db.Column(db.Boolean, default=False)
    is_active = db.Column(db.Boolean, default=True)
    display_order = db.Column(db.Integer, default=0)
    version = db.Column(db.String(20), default='1.0')
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f'<ConsentSettings {self.consent_type}>'
